[package]
name = "bitcoin_rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4"] }
chrono = "0.4"
tokio-util = "0.7.11"
futures-util = "0.3"
futures = "0.3"
bytes = "1"